version: 2

references:
  container_config: &container_config
    docker:
      - image: arti.tw.ee/circle_openjdk8:latest
        user: circleci
      - image: circleci/mariadb:10.3
        command: mysqld --max_allowed_packet=32m --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
          MYSQL_ROOT_PASSWORD: q1w2e3r4
          MYSQL_DATABASE: mydb
    resource_class: medium
    environment:
      TERM: vt100
      GRADLE_OPTS: '-Dorg.gradle.console=plain'
      IN_CIRCLE: true
  working_directory: &working_directory
    working_directory: ~/tw-entrypoints

jobs:
  build:
    <<: *working_directory
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          key: tw-entry-points-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - run:
          name: Assemble jar
          command: ./gradlew assemble --console=plain --no-daemon
      - run:
          name: Wait for Db Initialization
          command: dockerize -wait tcp://localhost:3306 -timeout 2m
      - run:
          name: Run tests
          command: ./gradlew check -Dspring.profiles.include=circle --console=plain --no-daemon --stacktrace
      - save_cache:
          paths:
            - ~/.gradle/
          key: tw-entry-points-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - store_test_results:
          path: ./tw-entry-points/build/test-results/
      - store_test_results:
          path: ./tw-entry-points-starter/build/test-results/
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  artifacts-publish:
    <<: *working_directory
    <<: *container_config
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/tw-entry-points
      - restore_cache:
          key: tw-entry-points-gradle-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - run:
          name: Set git config
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.name "TransferWise CircleCI" && git config --global user.email circle@circle.tw.ee
      - run:
          name: Publish artifacts
          command: ./gradlew publish pushTag --console=plain

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - artifacts-publish:
          context: artifactory-deploy
          requires:
            - build
          filters:
            branches:
              only:
                - master